apiVersion: v1
kind: Service
metadata:
  name: tienda-frontend
  namespace: tienda
  annotations:
    # Forzamos que sea público (no interno)
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  # EKS Auto Mode: el NLB lo provisiona el controlador nativo del clúster
  loadBalancerClass: eks.amazonaws.com/nlb
  selector:
    app: tienda-frontend
  ports:
    - port: 80
      targetPort: 80
